# Generated by Django 4.2.11 on 2024-04-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0004_notification_journey_alter_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.participation'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
