# Generated by Django 4.2.11 on 2024-04-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0006_alter_participation_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='background',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
