# Generated by Django 4.2.11 on 2024-05-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0009_commentjourney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='participation',
        ),
    ]
