# Generated by Django 4.2.11 on 2024-05-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0010_remove_notification_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estimated_time_of_arrival',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visit_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='VisitPoint',
        ),
    ]
