# Generated by Django 4.2.11 on 2024-05-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0012_comment_parent_comment_commentjourney_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
