# Generated by Django 4.2.11 on 2024-05-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0015_remove_report_reporter_remove_report_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='journeys.reporteduser'),
        ),
    ]
