# Generated by Django 4.2.11 on 2024-06-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0017_remove_participation_current_location_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
