# Generated by Django 4.2.11 on 2024-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0018_post_latitude_post_longitude_user_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
